Traceback (most recent call last):
  File "__init__.pxd", line 987, in numpy.import_array (referit/external/_mask.c:10001)
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 28, in <module>
    from referit_loader import ReferDataset
  File "/media/user_home2/j1k1000o/j1k/query-objseg/query-objseg/referit_loader.py", line 20, in <module>
    from referit import REFER
  File "/home/j1k1000o/anaconda3/lib/python3.6/site-packages/referit/__init__.py", line 9, in <module>
    from .refer import REFER
  File "/home/j1k1000o/anaconda3/lib/python3.6/site-packages/referit/refer.py", line 37, in <module>
    from referit.external import mask
  File "/home/j1k1000o/anaconda3/lib/python3.6/site-packages/referit/external/mask.py", line 3, in <module>
    import referit.external._mask as _mask
  File "referit/external/_mask.pyx", line 18, in init referit.external._mask (referit/external/_mask.c:11211)
  File "__init__.pxd", line 989, in numpy.import_array (referit/external/_mask.c:10044)
ImportError: numpy.core.multiarray failed to import
